slab_fft: slab_fft.cc helpers.h
	g++ -std=c++11 -Wall -Wextra -lfftw3f -O3 -o slab_fft slab_fft.cc

baseline_fftw: baseline_fftw.cc helpers.h
	g++ -std=c++11 -Wall -Wextra -lfftw3f -O3 -o baseline_fftw baseline_fftw.cc
